test:
  stage: test
  tags:
    - django-oscar
  image: $IMAGE
  script:
    - pip install tox
    - tox -e $TOX_ENVS
  parallel:
    matrix:
      - IMAGE: python:3.7
        TOX_ENVS: py37-django{220,310}-wagtail{211,212}

      - IMAGE: python:3.8
        TOX_ENVS: py38-django{220,310}-wagtail{211,212}

      - IMAGE: python:3.9
        TOX_ENVS: py39-django{220,310}-wagtail{211,212}

      - IMAGE: pypy:3
        TOX_ENVS: pypy3-django{220,310}-wagtail{211,212}
