include:
  - project: thelabnyc/gitlab-ci-templates
    file: /ci/sast.gitlab-ci.yml

test_python36:
  stage: test
  image: python:3.6
  script:
    - pip install tox
    - tox -e 'py36-django{111,210,220}-wagtail{23,25,26}'

test_python37:
  stage: test
  image: python:3.7
  script:
    - pip install tox
    - tox -e 'py37-django{210,220}-wagtail{23,25,26}'

test_pypy36:
  stage: test
  image: pypy:3-6
  script:
    - pip install tox
    - tox -e 'pypy3-django{111,210,220}-wagtail{23,25,26}'
